spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ubuntu:5432/nark
    username: spark
    password: spark
  thymeleaf:
    cache: false
logging:
  level:
    jp.gr.java_conf.star_diopside.nark: debug
