spring:
  messages:
    basename: messages, ValidationMessages
  session:
    store-type: jdbc
security:
  filter-dispatcher-types: ASYNC, FORWARD, REQUEST
liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml
